# Generated by Django 5.0.7 on 2024-07-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentAI', '0002_formdata_submission_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submission_info',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='formdata',
            name='sentiment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='subject',
            field=models.TextField(max_length=255),
        ),
    ]
