# Generated by Django 5.0.7 on 2024-08-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentAI', '0003_delete_submission_info_remove_formdata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.TextField(max_length=255)),
                ('email_content', models.TextField()),
            ],
        ),
    ]
